version: "3"

services:

  iot:
    image: corka149/iotserver:latest
    environment:
      IOT_SERVER_PROFILE: docker
    ports:
      - 8000:8000

  mongo:
    image: mongo:4.4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: s3cr3t
      MONGO_INITDB_DATABASE: iot
    ports:
      - 27017:27017

  redis:
    image: redis:6
    ports:
    - 6379:6379
    command: redis-server --requirepass "p4ssw0rd"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_PASSWORD=p4ssw0rd
    ports:
    - "8081:8081"
